---
title: "CMPD Officer Involved Shooting Incidents"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---


Map View
=====================================

```{r setup, include=FALSE}
library(leaflet)
library(readr)
library(DT)
library(plotly)

shooting_data <- read_csv('cleaned_data.csv')


#let's add a popup_html field - 
#HTML that will display when user clicks on an incident

shooting_data$popup_html <- paste0("<style> div.leaflet-popup-content {width:500px !important;}</style>",
                                   "<b>Date: </b> ", shooting_data$YEAR_MONTH, "<br/>",
                                   "<b>Location: </b>", shooting_data$LOCATION, "<br/>",
                                   "<b>DA Legal Review: </b>", shooting_data$DA_LEGAL_REVIEW, "<br/>",
                                   "<b>Fatal Injury? </b>", shooting_data$Fatal_Injury, "<br/>",
                                   "<b>Non Fatal Injury? </b>", shooting_data$Non_Fatal_Injury, "<br/>",
                                   "<b>Shots fired & Missed? </b>", shooting_data$Miss, "<br/> <br/>",
                                   "<b>Narrative: </b>", shooting_data$NARRATIVE)

map <- leaflet(data = shooting_data) %>%  
  addTiles() %>% 
  setView(lng = -80.8431, lat = 35.2271, zoom = 10) %>%
  addMarkers(~long, ~lat, popup = ~as.character(popup_html))


```


Inputs {.sidebar}
-------------------------------------

###Filters

```{r}


  checkboxGroupInput("policy_violation", "Officer Policy Violation",
                     c("Yes" = "yes_violation",
                       "No" = "no_violation"),
                     selected = c("yes_violation", "no_violation"))


  checkboxGroupInput("officer_demographics", "Officer Demographics",
                     c("White" = "white_officer",
                       "Black" = "black_officer",
                       "Asian" = "asian_officer",
                       "Hispanic" = "hispanic_officer",
                       "American Indian" = "indian_officer",
                       "Male" = "male_officer",
                       "Female" = "female_officer"),
                     
                     selected = c("white_officer", "black_officer", "asian_officer", "hispanic_officer",
                                  "indian_officer", "male_officer", "female_officer"))

  checkboxGroupInput("individual_demographics", "Individual Demographics",
                     c("White" = "white_individual",
                       "Black" = "black_individual",
                       "Asian" = "asian_individual",
                       "Hispanic" = "hispanic_individual",
                       "Unknown" = "unknown_individual",
                       "Male" = "male_individual",
                       "Female" = "female_individual"),
                     
                     selected = c("white_individual", "black_individual", "asian_individual",
                                  "hispanic_individual", "unknown_individual", "male_individual",
                                  "female_individual") )

  
    checkboxGroupInput("injury_type", "Injuries Suffered",
                     c("Fatal Injury" = "fatal_injury",
                       "Non Fatal Injury" = "non_fatal_injury",
                       "None (Shots Missed)" = "no_injury"),
                     
                     selected = c("fatal_injury", "non_fatal_injury", "no_injury"))
  
```


Column {data-width=650}
-----------------------------------------------------------------------

### Charlotte Officer Involved Shootings: 2005 - 2016
```{r}
map
```

Column {data-width=350}
-----------------------------------------------------------------------

### Incidents Per Year

```{r}
plt_data <- shooting_data %>% 
  mutate(Year = substr(YEAR_MONTH, 1, 4)) %>% 
  group_by(Year) %>% 
  summarise(Incidents = n())


plt <- ggplot(data = plt_data, aes(x = Year, y = Incidents)) + geom_bar(stat = "identity", fill = "blue") + ggtitle("Officer Involved Shooting Incidents By Year") + scale_y_continuous(breaks = c(seq(0,12, 1)))

ggplotly(plt) 
  

```

### Placeholder

```{r}
#TODO: add code to display narrative here
```


Raw Data View
=====================================

### Raw Data
```{r}
dt <- shooting_data %>% 
  select(-(popup_html), -(lat), -(long))

datatable(dt, options = list(
  autoWidth = TRUE,
  columnDefs = list(list(width = '400px', targets = c(5))) )) 
```

